### ISSUE TITLE
Won't compile with RGBDS v0.5.2 as suggested, but compiles fine using RGBDS v0.6.0

### ISSUE THREAD

**Issue by JayroJones** [pret/pokepinball#52]
Thought it would be worth mentioning for anyone wanting to compile under Cygwin64 for 64-bit Windows using 64-bit RGBDS.

Same thing goes for the [Pokepinball-generations](https://github.com/huderlem/pokepinball-generations) decompilation project.

**Comment by Xillicis** [comment]
This might be an obsolete issue now that we are getting on Version 0.9.0 of rgbds.
